import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await (await browser.newContext({ viewport: { width: 915, height: 412 }, hasTouch: true, isMobile: true })).newPage();
await page.addInitScript(() => localStorage.setItem('lecraft.settings.v1', JSON.stringify({ quality: 'MEDIUM', renderDistance: 5, autoQuality: false, gfxV: 2 })));
await page.goto('http://localhost:4173/');
await page.waitForFunction(() => window.__lecraft?.state === 'menu');
const mode = process.env.MODE ?? 'world';
if (mode === 'server') await page.evaluate(() => window.__lecraft.joinServer());
else await page.evaluate(() => window.__lecraft.createWorld('P', '839274928', 'survival', 'normal'));
await page.waitForFunction(() => window.__lecraft?.state === 'playing' && window.__lecraft.session.loaded, null, { timeout: 120000 });
await page.waitForTimeout(4000);
const cdp = await page.context().newCDPSession(page);
await cdp.send('Profiler.enable');
await cdp.send('Profiler.setSamplingInterval', { interval: 200 });
await cdp.send('Profiler.start');
await page.evaluate(() => { const g = window.__lecraft; g.input.moveY = 1; g.input.sprint = true; });
await page.waitForTimeout(12000);
const { profile } = await cdp.send('Profiler.stop');
const self = new Map();
const byId = new Map(profile.nodes.map((n) => [n.id, n]));
const dt = profile.timeDeltas; const counts = new Map();
profile.samples.forEach((id, i) => counts.set(id, (counts.get(id) ?? 0) + (dt[i] ?? 0)));
for (const [id, t] of counts) { const n = byId.get(id); const k = `${n.callFrame.functionName || '(anon)'} ${n.callFrame.url.split('/').pop()}:${n.callFrame.lineNumber}`; self.set(k, (self.get(k) ?? 0) + t); }
const total = [...self.values()].reduce((a, b) => a + b, 0);
console.log([...self].sort((a, b) => b[1] - a[1]).slice(0, 30).map(([k, t]) => `${(t / total * 100).toFixed(1)}%  ${k}`).join('\n'));
await browser.close();
